/**
 * Re-exports of all types used by the Platform Bridge.
 * Consumers should import types from '@/types/tauri' directly;
 * this file exists for bridge-internal use.
 */
export type {
  ApiKeyRecord,
  ApiKeyCreatePayload,
  ApiKeyMutationResponse,
  ApiKeyDeleteResponse,
  ApiKeyValidationResponse,
  ExperimentDeleteResponse,
  ExperimentDetailMetaResponse,
  RawTablePageResponse,
  BackupInfo,
  BackupResult,
  ExperimentsExportToFileResponse,
  ExperimentGetResponse,
  ExperimentsImportResponse,
  ExperimentsLaboratoriesResponse,
  ExperimentSaveResponse,
  ExperimentsCountResponse,
  ExperimentsFilterMetadataResponse,
  ExperimentsListQuery,
  ExperimentsListResponse,
  LastContextResponse,
  ReagentDeleteResponse,
  ReagentMutationResponse,
  ReagentRecord,
  ReagentsExportResponse,
  ReagentsImportResponse,
  ReagentUpsertPayload,
  OperatorRecord,
  OperatorUpsertPayload,
  OperatorMutationResponse,
  OperatorDeleteResponse,
  LaboratoryRecord,
  LaboratoryUpsertPayload,
  LaboratoryMutationResponse,
  LaboratoryDeleteResponse,
  WaterSourcesResponse,
  FixtureSummaryResponse,
  FixtureReadResponse,
  ParseFileRequest,
  ParseFileResponse,
  JobRecord,
  JobCancelResponse,
  AnalysisCacheStats,
  AnalysisCachePruneResponse,
  ExperimentProjectionStatus,
  ExperimentProjectionRebuildResponse,
  PlatformType,
  PlatformBridge,
} from '@/types/tauri';
export type { SeriesMetaResponse, SeriesWindow } from '@/lib/series/binary-series';
