// Auto-generated by specta — do NOT edit manually.
// Run `cargo test export_ts_bindings` in src-tauri/ to regenerate.
// DO NOT edit this file manually.

export type ActiveApiKeyMeta = { id: string; name: string; isActive: boolean; createdAt: string }

export type ActiveApiKeyResponse = { provider: string; count: number; activeKey?: ActiveApiKeyMeta | null; error?: string | null }

export type AiAppliedMappingEntry = { field: string; index: number; confidence?: number | null }

export type AiDiagnostics = { attempted: boolean; provider: string; model: string; promptVersion: string; candidateCount: number; selectedCandidate?: number | null; status: AiDiagnosticsStatus; failureReason?: string | null; appliedMapping?: AiAppliedMappingEntry[] }

export type AiDiagnosticsStatus = "accepted" | "failed" | "rejected"

export type AnalysisCachePruneResponse = { maxTotalBytes: number; deletedRows: number; before: AnalysisCacheStats; after: AnalysisCacheStats }

export type AnalysisCacheStats = { totalRows: number; totalBytes: number; accessedRows: number; oldestUpdatedAt: string | null; newestUpdatedAt: string | null; newestAccessedAt: string | null }

export type ApiKeyCreatePayload = { name: string; key: string; provider: string | null }

export type ApiKeyDeleteResponse = { success: boolean; error?: string | null }

export type ApiKeyItem = { id: string; name: string; key: string; provider: string; isActive: boolean; createdAt: string; updatedAt: string; 
/**
 * `false` when the stored ciphertext could not be decrypted on the
 * current machine — the row is still visible in the list (audit-v2
 * SEC-003 turned this into a non-destructive flag) so the user can
 * see the orphan and choose to delete or re-create.  Defaults to
 * `true` for newly-created/updated keys (those go through `encode_key`
 * successfully by definition).
 */
isDecryptable?: boolean }

export type ApiKeyMutationResponse = { success: boolean; key?: ApiKeyItem | null; error?: string | null }

export type ApiKeyValidationResponse = { isValid: boolean; error?: string | null }

/**
 * Information about a backup file
 */
export type BackupInfo = { name: string; date: string; size: number }

/**
 * Result of a backup operation
 */
export type BackupResult = { success: boolean; name?: string | null; error?: string | null }

export type CalibrationResponse = { deviceType: string; rSquared: number; slope: number; intercept: number; hysteresis: number; stdev: number; status: string; lastCalDate?: string | null; calibrationDate?: string | null; issues: string[]; rawData: string }

export type ComparisonByIdsAnalysisSettings = { pointsToAverage?: number; viscosityShearRates?: number[] }

export type ComparisonByIdsChartConfig = { metrics: ComparisonByIdsMetrics; axisMode: string; brushRange?: [number, number] | null; touchPoint: ComparisonByIdsTouchPointConfig; lineSettings: ComparisonByIdsChartLineSettings; experimentColors: string[]; timeFormat?: string; downsampleMode?: string; chartWidth?: number; chartHeight?: number }

export type ComparisonByIdsChartLineSettings = { viscosity?: ComparisonByIdsLineSettings; temperature?: ComparisonByIdsLineSettings; shearRate?: ComparisonByIdsLineSettings; pressure?: ComparisonByIdsLineSettings; rpm?: ComparisonByIdsLineSettings; bathTemperature?: ComparisonByIdsLineSettings | null }

export type ComparisonByIdsDetectionSettings = { shearRateTolerance?: number; shearRateRelTolerance?: number; minStepDuration?: number; stepSplitting?: boolean; splitStartDuration?: number; splitEndDuration?: number; minDurationForSplit?: number }

export type ComparisonByIdsLineSettings = { color?: string; width?: number; style?: string }

export type ComparisonByIdsMetrics = { primary: string; leftSecondary: string; secondary: string; tertiary: string }

export type ComparisonByIdsReportSettings = { showTemperature: boolean; showShearRate: boolean; showPressure: boolean; showBathTemperature: boolean; shearRateAxis: string; pressureAxis: string; showAdvancedStats: boolean; reportViscosityRates: number[]; rheologyUnits?: ComparisonByIdsRheologyUnits | null }

export type ComparisonByIdsRheologyUnits = { viscosity?: string; temperature?: string; pressure?: string; consistency?: string; plasticViscosity?: string; yieldPoint?: string; timeFormat?: string }

export type ComparisonByIdsSectionToggles = { showCalibration: boolean; showRawData: boolean; showRecipe: boolean; showWaterAnalysis: boolean; showRheology?: boolean }

export type ComparisonByIdsTouchPointConfig = { enabled: boolean; viscosityThreshold: number; showTargetTime: boolean; targetTime: number }

export type ComparisonReportByIdsRequest = { experimentIds: string[]; settings: ComparisonReportByIdsSettings }

export type ComparisonReportByIdsSettings = { language: string; unitSystem: string; companyName?: string | null; companyLogoBase64?: string | null; generatedAt?: string | null; comparisonChart: ComparisonByIdsChartConfig; sectionToggles: ComparisonByIdsSectionToggles; reportSettings: ComparisonByIdsReportSettings; analysisSettings?: ComparisonByIdsAnalysisSettings; detectionSettings?: ComparisonByIdsDetectionSettings }

export type ConflictItem = { id: string; mergeEventId: string | null; experimentId: string | null; fieldName: string; localValue: string | null; incomingValue: string | null; resolution: string | null; status: string; createdAt: string; resolvedAt: string | null }

export type ExperimentDeleteResponse = { success: boolean; error?: string | null }

export type ExperimentDetailMeta = { id: string; createdAt: string; updatedAt: string; name: string; fieldName: string | null; operatorName: string | null; wellNumber: string | null; testId: string | null; originalFilename: string; testDate: string; instrumentType: string; geometry: string | null; geometrySource: string | null; waterSource: string; waterParams: JsonValue | null; fluidType: string; testGroup: string; testSubGroup: string | null; testCategory?: string | null; testType?: string | null; dominantPattern?: string | null; metrics: JsonValue; calibration: JsonValue | null; reagents: StoredExperimentReagent[]; summary: ExperimentDetailSummary; user: StoredExperimentUser | null; laboratory: StoredExperimentLaboratory | null; parsedBy?: string | null; parseSource?: string | null; extraFields?: JsonValue | null }

export type ExperimentDetailMetaResponse = { success: boolean; experiment?: ExperimentDetailMeta | null; error?: string | null }

export type ExperimentDetailSummary = { pointCount: number; timeRangeMin?: number | null; timeRangeMax?: number | null; viscosityMin?: number | null; maxViscosity?: number | null; avgViscosity?: number | null; pressureMax?: number | null }

/**
 * Lightweight existence check — returns only the IDs that exist in the DB.
 */
export type ExperimentExistenceResponse = { existingIds: string[] }

export type ExperimentGetBatchResponse = { success: boolean; experiments: StoredExperiment[]; error?: string | null }

export type ExperimentGetResponse = { success: boolean; experiment?: StoredExperiment | null; error?: string | null }

/**
 * Lightweight experiment summary for list/table views.
 * Excludes heavy payloads: rawPoints, metrics, calibration.
 */
export type ExperimentListItem = { id: string; createdAt: string; updatedAt: string; name: string; fieldName: string | null; operatorName: string | null; wellNumber: string | null; testId: string | null; originalFilename: string; testDate: string; instrumentType: string; geometry: string | null; geometrySource: string | null; waterSource: string; waterParams: JsonValue | null; fluidType: string; testGroup: string; testSubGroup: string | null; testCategory?: string | null; testType?: string | null; dominantPattern?: string | null; maxViscosity: number | null; avgViscosity: number | null; durationSeconds: number | null; avgTemperatureC: number | null; maxTemperatureC: number | null; touchHasCrossing?: boolean | null; touchCrossingTimeMin?: number | null; touchCrossingViscosityCp?: number | null; touchViscosityAtTargetCp?: number | null; touchPrecomputeVersion?: number | null; reagents: StoredExperimentReagent[]; user: StoredExperimentUser | null; laboratory: StoredExperimentLaboratory | null }

export type ExperimentPayloadItem = { id: string; experimentId: string; importBatchId: string | null; payloadVersion: number; payloadFormat: string; contentFingerprint: string; sourceLabId: string | null; isCanonical: boolean; createdAt: string }

export type ExperimentProjectionRebuildResponse = { before: ExperimentProjectionStatus; after: ExperimentProjectionStatus; rebuiltRows: number; facetRebuild: FacetRebuildResult }

export type ExperimentProjectionStatus = { experimentCount: number; projectionCount: number; currentProjectionCount: number; missingOrStaleCount: number; facetCount: number; facetDirty: boolean; projectionVersion: number; lastFullRebuildAt: string | null; lastFacetRebuildAt: string | null; ready: boolean }

export type ExperimentReportByIdRequest = { experimentId: string; settings: ComparisonReportByIdsSettings; recipeOverride?: ExperimentReportRecipeOverride[] | null; waterOverride?: ExperimentReportWaterOverride | null }

export type ExperimentReportRecipeOverride = { name: string; concentration: number; unit: string; category?: string | null; batchNumber?: string | null }

export type ExperimentReportWaterOverride = { source?: string | null; salinity?: number | null; ph?: number | null; hardness?: number | null; fe?: number | null; ca?: number | null; mg?: number | null; cl?: number | null; so4?: number | null; hco3?: number | null }

export type ExperimentSavePayload = { name: string; fieldName: string | null; operatorName: string | null; wellNumber: string | null; testId: string | null; originalFilename: string; testDate: string; instrumentType: string; geometry: string | null; geometrySource: string | null; waterSource: string; waterParams: JsonValue | null; fluidType: string; testGroup: string; testSubGroup: string | null; testCategory?: string | null; testType?: string | null; dominantPattern?: string | null; metrics: JsonValue; rawPoints?: JsonValue[]; calibration: JsonValue | null; reagents?: StoredExperimentReagent[]; overwrite: boolean | null; laboratoryId?: string | null; parsedBy?: string | null; parseSource?: string | null; timeRangeMin?: number | null; timeRangeMax?: number | null; viscosityMin?: number | null; pressureMax?: number | null; extraFields?: JsonValue | null }

export type ExperimentSaveResponse = { success: boolean; experimentId?: string | null; message?: string | null; error?: string | null; code?: string | null }

export type ExperimentsCountResponse = { count: number }

export type ExperimentsFilterMetadataResponse = { instrumentTypes: string[]; fluidTypes: string[]; geometries: string[]; reagentNames: string[]; laboratoryNames: string[]; fieldNames: string[]; waterSources: string[]; testCategories: string[]; testTypes: string[]; 
/**
 * Library-wide coverage / range stats for the touch-point precomputed
 * columns.  Used by the UI to:
 * * Show "в БД: X..Y" hints beneath each touch-point range filter so
 * users pick sensible values instead of filtering to zero rows.
 * * Render a contextual empty-state when a touch-point filter hides
 * everything ("из 220 эксп. только 1 достиг порога 50 сП…").
 * Computed against the WHOLE library — independent of the current
 * filter panel selections — so the hints remain stable while the user
 * is editing filter values.
 */
touchPointStats: TouchPointLibraryStats }

export type ExperimentsListQuery = { page?: number | null; limit?: number | null; laboratoryId?: string | null; searchQuery?: string | null; testName?: string | null; laboratoryName?: string | null; fieldName?: string | null; operatorName?: string | null; wellNumber?: string | null; waterSource?: string | null; fluidType?: string | null; instrumentType?: string | null; geometry?: string | null; batchNumber?: string | null; reagentName?: string | null; reagentNames?: string[] | null; dateFrom?: string | null; dateTo?: string | null; durationMin?: string | null; durationMax?: string | null; tempMin?: string | null; tempMax?: string | null; viscosityMin?: string | null; viscosityMax?: string | null; testCategory?: string | null; testType?: string | null; 
/**
 * Lower bound for `touchCrossingTimeMin` (minutes).
 */
crossingTimeMin?: string | null; 
/**
 * Upper bound for `touchCrossingTimeMin` (minutes).
 */
crossingTimeMax?: string | null; 
/**
 * Lower bound for `touchCrossingViscosityCp` (centipoise, cP).
 */
crossingViscosityMin?: string | null; 
/**
 * Upper bound for `touchCrossingViscosityCp` (centipoise, cP).
 */
crossingViscosityMax?: string | null; 
/**
 * Lower bound for `touchViscosityAtTargetCp` (centipoise, cP).
 */
viscosityAtTargetMin?: string | null; 
/**
 * Upper bound for `touchViscosityAtTargetCp` (centipoise, cP).
 */
viscosityAtTargetMax?: string | null; 
/**
 * Tri-state selector over the precomputed `touchHasCrossing` flag.
 * Accepts `"yes"`, `"no"`, or empty / missing (= no filter).  Any other
 * value is ignored by the query builder rather than producing an error,
 * matching the permissive string-based contract of the other filters.
 */
hasCrossing?: string | null; 
/**
 * Viscosity threshold (cP) for the touch-point filter — user input.
 * 
 * When **set** to a positive number, the query builder leaves the
 * precomputed `touchHasCrossing` / `touchCrossingTimeMin` columns
 * alone and instead re-runs the smart-touch-point algorithm against
 * each candidate experiment with this threshold.  This unlocks lab
 * workflows where the "gel break-point" isn't the default 50 cP
 * (e.g. crosslinked fluids often break at 500 cP).  Computation is
 * O(N·points) per query but coarse-pruned by `maxViscosity >= threshold`
 * so only plausibly-crossing rows hit the algorithm.
 * 
 * When **omitted / empty / non-numeric**, the fast precomputed path
 * for the library-fixed 50 cP threshold is used.
 */
viscosityThreshold?: string | null; 
/**
 * Keyset cursor: when set, skip OFFSET and instead use WHERE e.createdAt < cursor_date
 * OR (e.createdAt = cursor_date AND e.id > cursor_id). Takes priority over `page`.
 */
afterId?: string | null; 
/**
 * Column to sort by. Validated server-side against an explicit whitelist.
 * Ignored when using keyset cursor (cursor requires deterministic ordering).
 */
sortBy?: string | null; 
/**
 * Sort direction: "asc" or "desc". Defaults to "desc" when absent.
 */
sortDir?: string | null }

export type ExperimentsListResponse = { experiments: ExperimentListItem[]; pagination: ExperimentsPagination }

export type ExperimentsPagination = { page: number; limit: number; total: number; totalPages: number; 
/**
 * Last item ID from this page — pass as `afterId` in next request
 * for keyset (cursor-based) pagination instead of OFFSET.
 */
nextCursor?: string | null }

export type FacetRebuildResult = { facetRows: number; updatedAt: string }

export type FilenameMetadataResponse = { testId?: string | null; testType?: string | null; testTypeFull?: string | null; fieldName?: string | null; destination?: string | null; waterSource?: string | null; temperature?: number | null; recipe?: RecipeComponentResponse[] | null }

export type FixtureItem = { name: string; displayName: string }

export type FixtureReadResponse = { success: boolean; filename?: string | null; bytes?: number[] | null; error?: string | null }

export type FixturesListResponse = { success: boolean; fixtures: FixtureItem[]; count: number; error?: string | null }

export type ImportBatchItem = { id: string; sourceLabId: string | null; sourceSystem: string | null; sourceAppVersion: string | null; importedByUserId: string | null; fileName: string | null; checksum: string | null; notes: string | null; experimentsImported: number; duplicatesDetected: number; status: string; createdAt: string; updatedAt: string }

export type JobCancelResponse = { jobId: string; status: JobStatus; cancelled: boolean }

export type JobFinishedEvent = { jobId: string; kind: JobKind; status: JobStatus; error: string | null; metrics: JobMetrics | null }

export type JobKind = "comparisonPdf" | "comparisonExcel" | "singlePdf" | "singleExcel" | "importDb" | "backupRestore" | "analysisCachePrune" | "analysisCacheWarmup" | "experimentProjectionRebuild" | "experimentFacetRebuild" | "maintenance"

export type JobMetrics = { queuedMs: number; wallMs: number; cpuMsDelta: number | null; rssMbStart: number | null; rssMbPeak: number | null; rssMbEnd: number | null; cacheHits: number | null; cacheMisses: number | null; artifactBytesRead: number | null; artifactBytesWritten: number | null; outputBytes: number | null }

export type JobProgress = { phase: string; current: number; total: number | null; message: string | null }

export type JobProgressEvent = { jobId: string; kind: JobKind; status: JobStatus; phase: string; current: number; total: number | null; message: string | null }

export type JobRecord = { id: string; kind: JobKind; status: JobStatus; createdAt: string; startedAt: string | null; finishedAt: string | null; progress: JobProgress; error: string | null; metrics: JobMetrics | null }

export type JobStatus = "queued" | "running" | "cancelling" | "cancelled" | "succeeded" | "failed"

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

export type LaboratoryDeleteResponse = { success: boolean; error?: string | null }

export type LaboratoryMutationResponse = { success: boolean; laboratory?: StoredLaboratory | null; error?: string | null }

export type LaboratoryUpsertPayload = { name: string; description?: string | null; location?: string | null }

export type LastContextReagent = { reagentId: string; reagentName: string; concentration: number; unit: string; batchNumber: string | null; productionDate: string | null }

export type LastContextResponse = { fieldName: string | null; operatorName: string | null; waterSource: string | null; reagents: LastContextReagent[] }

/**
 * The authoritative result of a license check, computed in Rust.
 * Sent to the frontend as a single atomic snapshot.
 */
export type LicenseCheckResult = { status: LicenseStatus; source: LicenseSource; features: LicenseFeatures; 
/**
 * License key (masked for display, e.g. "RHEO-****-****-ABCD")
 */
key: string | null; 
/**
 * License type string from server
 */
licenseType: string | null; 
/**
 * Customer name from license
 */
customerName: string | null; 
/**
 * License expiry date (ISO 8601)
 */
expiresAt: string | null; 
/**
 * Days remaining until expiry (negative = past due)
 */
daysRemaining: number | null; 
/**
 * Experiments remaining (demo mode only)
 */
experimentsRemaining: number | null; 
/**
 * Human-readable message
 */
message: string | null; 
/**
 * Whether the UI should show a warning banner
 */
showWarning: boolean }

/**
 * Feature flags determining what the user can do.
 */
export type LicenseFeatures = { maxExperiments: number; maxComparisonExperiments: number; exportPdf: boolean; exportExcel: boolean; aiParsing: boolean; comparison: boolean; watermark: boolean; calibrationAnalysis: boolean; calibrationParsing: boolean; chandler5550Support: boolean; bslR1Support: boolean }

/**
 * Where the license came from
 */
export type LicenseSource = "key" | "demo"

/**
 * Authoritative license status determined entirely in Rust.
 */
export type LicenseStatus = 
/**
 * Full license is active and valid
 */
"active" | 
/**
 * License expired but within grace period
 */
"grace" | 
/**
 * Demo trial is active
 */
"demo" | 
/**
 * Demo trial has expired
 */
"demo_expired" | 
/**
 * License has expired (past grace period)
 */
"expired" | 
/**
 * License is invalid / tampered / revoked
 */
"invalid" | 
/**
 * License was revoked by the server
 */
"revoked"

/**
 * License type (matches server-side types).
 * 
 * Release-channel mapping used by `get_update_channel`:
 * 
 * | License type | Update channel | Who receives builds first |
 * |--------------|----------------|---------------------------|
 * | `Superuser`  | `alpha`        | Project owner (personal QA tier) |
 * | `Developer`  | `beta`         | Internal dev team |
 * | everything   | `stable`       | End users |
 * 
 * The alpha → beta → stable promotion is a **manual** pipeline: the owner
 * ships a build to `alpha`, validates it on their machine, then promotes it
 * to `beta`; once the dev team confirms, it moves to `stable`.
 */
export type LicenseType = "demo" | "trial" | "standard" | "enterprise" | "developer" | 
/**
 * Top-tier personal licence for the project owner. Receives builds on
 * the `alpha` channel before Developer licences see them on `beta`.
 */
"superuser"

/**
 * Result of a database merge (import) operation
 */
export type MergeResult = { success: boolean; error?: string | null; 
/**
 * Number of experiments added from the import source
 */
imported: number; 
/**
 * Number of experiments skipped (already existed)
 */
skipped: number }

export type OperatorDeleteResponse = { success: boolean; error?: string | null }

export type OperatorMutationResponse = { success: boolean; operator?: StoredOperator | null; error?: string | null }

export type OperatorUpsertPayload = { name: string; position?: string | null }

export type ParseFileResponse = { success: boolean; source: string; data: ParsedPoint[]; metadata: ParseMetadata; summary: ParseSummary }

export type ParseMetadata = { filename: string; instrumentType?: string | null; geometry?: string | null; geometrySource?: string | null; usedAI: boolean; testDate?: string | null; aiDiagnostics?: AiDiagnostics | null; filenameMetadata?: FilenameMetadataResponse | null; calibration?: CalibrationResponse | null }

export type ParseRequest = { filename: string; 
/**
 * Preferred on desktop: Rust reads the file from disk — avoids 8× JSON array conversion over IPC.
 */
filePath: string | null; 
/**
 * Web / WASM fallback only — present when filePath is absent.
 */
bytes: number[] | null; 
/**
 * When true, skip heuristic parsing and use Groq AI for column mapping.
 */
forceAi: boolean | null; 
/**
 * AI model override (defaults to llama-4-scout).
 */
aiModel: string | null }

export type ParseSummary = { pointCount: number; timeRange?: TimeRange | null; viscosityRange?: SummaryRangeWithAvg | null; temperatureRange?: SummaryRangeWithAvg | null; pressureRange?: SummaryRange | null }

export type ParsedPoint = { time_sec: number; viscosity_cp: number; temperature_c: number; speed_rpm: number; shear_rate_s1: number; shear_stress_pa: number; pressure_bar: number; bath_temperature_c?: number | null }

export type ParserArtifactItem = { id: string; experimentId: string; importBatchId: string | null; parserVersion: string; schemaVersion: string; contentFingerprint: string; promotedToHot: boolean; createdAt: string }

export type ProjectionRebuildBatchResult = { processed: number; lastExperimentId: string | null; hasMore: boolean }

export type RawTablePage = { experimentId: string; totalRows: number; page: number; pageSize: number; totalPages: number; hasBathTemperature: boolean; rows: RawTableRow[] }

export type RawTablePageResponse = { success: boolean; page?: RawTablePage | null; error?: string | null }

export type RawTableRow = { index: number; timeSec: number | null; viscosityCp: number | null; temperatureC: number | null; speedRpm: number | null; shearRateS1: number | null; shearStressPa: number | null; pressureBar: number | null; bathTemperatureC: number | null }

export type ReagentDeleteResponse = { success: boolean; error?: string | null }

export type ReagentMutationResponse = { success: boolean; reagent?: StoredReagent | null; error?: string | null }

export type ReagentUpsertPayload = { name: string; category: string; manufacturer: string | null; country: string | null; description: string | null; activeSubstance: string | null; form: string | null }

export type RecipeComponentResponse = { abbreviation: string; concentration: number; unit: string; category?: string | null; reagentId?: string | null; reagentName?: string | null }

export type ReportArtifactItem = { id: string; experimentId: string; importBatchId: string | null; reportType: string; templateVersion: string | null; storagePath: string | null; binarySha256: string | null; sizeBytes: number | null; createdAt: string }

export type SeriesMetaResponse = { experimentId: string; pointCount: number; timeMinSec: number | null; timeMaxSec: number | null; availableMetrics: SeriesMetricDescriptor[]; dataHash: string }

export type SeriesMetricDescriptor = { id: number; key: string }

export type SimpleResult = { success: boolean; message: string | null; error: string | null; deletedCount: number | null }

export type StoredExperiment = { id: string; createdAt: string; updatedAt: string; name: string; fieldName: string | null; operatorName: string | null; wellNumber: string | null; testId: string | null; originalFilename: string; testDate: string; instrumentType: string; geometry: string | null; geometrySource: string | null; waterSource: string; waterParams: JsonValue | null; fluidType: string; testGroup: string; testSubGroup: string | null; testCategory?: string | null; testType?: string | null; dominantPattern?: string | null; metrics: JsonValue; rawPoints: JsonValue[]; calibration: JsonValue | null; reagents: StoredExperimentReagent[]; maxViscosity: number | null; avgViscosity: number | null; user: StoredExperimentUser | null; laboratory: StoredExperimentLaboratory | null; parsedBy?: string | null; parseSource?: string | null; timeRangeMin?: number | null; timeRangeMax?: number | null; viscosityMin?: number | null; pressureMax?: number | null; extraFields?: JsonValue | null }

export type StoredExperimentLaboratory = { id: string; name: string }

export type StoredExperimentReagent = { reagentId: string | null; reagentName: string | null; concentration: number; unit: string; batchNumber: string | null; productionDate: string | null; category: string | null; reagent: StoredReagentDescriptor | null }

export type StoredExperimentUser = { id: string; name: string; email: string | null }

export type StoredLaboratory = { id: string; name: string; description?: string | null; location?: string | null; createdAt: string; updatedAt: string }

export type StoredOperator = { id: string; name: string; position?: string | null; isActive: boolean; createdAt: string; updatedAt: string }

export type StoredReagent = { id: string; name: string; category: string; manufacturer: string | null; country: string | null; description: string | null; activeSubstance: string | null; form: string | null; createdAt: string; updatedAt: string }

export type StoredReagentDescriptor = { name: string; category: string | null }

export type SummaryRange = { min: number; max: number }

export type SummaryRangeWithAvg = { min: number; max: number; avg: number }

export type SyncInboxItem = { id: string; remoteEventId: string; sourceLabId: string | null; sourceSystem: string | null; status: string; receivedAt: string; processedAt: string | null; importBatchId: string | null }

export type SyncOutboxItem = { id: string; entityType: string; entityId: string; operation: string; status: string; retryCount: number; nextAttemptAt: string | null; lastError: string | null; createdAt: string; processedAt: string | null }

export type SyncStatusResponse = { outboxPending: number; outboxFailed: number; inboxPending: number; conflictsOpen: number; lastSyncAt: string | null }

export type TimeRange = { start: number; end: number; durationMinutes: number }

/**
 * Library-wide touch-point coverage snapshot.
 * 
 * All range bounds are `Option` because they're only defined when at
 * least one row has a non-NULL value for the underlying column:
 * * `crossing_*`  — populated only for rows where the smoothed
 * viscosity actually crossed the library threshold (50 cP).
 * * `viscosity_at_target_*` — populated when the experiment runs
 * long enough to have a sample at / past the 10-min target.
 * 
 * When the library is empty these are all `None` and
 * `total_experiments == 0`; the UI treats that as "скрыть подсказки".
 */
export type TouchPointLibraryStats = { 
/**
 * Total experiments in the library (same as `experiments_count`).
 */
totalExperiments: number; 
/**
 * Number of experiments whose smoothed viscosity crossed the
 * library-fixed threshold (50 cP) — i.e. `touchHasCrossing = 1`.
 */
withCrossingCount: number; 
/**
 * Number of experiments that have a non-NULL
 * `touchViscosityAtTargetCp` (i.e. the curve extends to / past
 * the 10-min target).
 */
withTargetViscosityCount: number; 
/**
 * Observed minimum of `touchCrossingTimeMin` in minutes.
 */
crossingTimeMinMinutes: number | null; 
/**
 * Observed maximum of `touchCrossingTimeMin` in minutes.
 */
crossingTimeMaxMinutes: number | null; 
/**
 * Observed minimum of `touchCrossingViscosityCp` in centipoise.
 */
crossingViscosityMinCp: number | null; 
/**
 * Observed maximum of `touchCrossingViscosityCp` in centipoise.
 */
crossingViscosityMaxCp: number | null; 
/**
 * Observed minimum of `touchViscosityAtTargetCp` in centipoise.
 */
viscosityAtTargetMinCp: number | null; 
/**
 * Observed maximum of `touchViscosityAtTargetCp` in centipoise.
 */
viscosityAtTargetMaxCp: number | null }

export type WaterSourcesResponse = { waterSources: string[] }

