// Auto-generated by specta — do NOT edit manually.
// Run `cargo test export_ts_bindings` in src-tauri/ to regenerate.
// DO NOT edit this file manually.

export type ActiveApiKeyMeta = { id: string; name: string; isActive: boolean; createdAt: string }

export type ActiveApiKeyResponse = { provider: string; count: number; activeKey?: ActiveApiKeyMeta | null; error?: string | null }

export type AiAppliedMappingEntry = { field: string; index: number; confidence?: number | null }

export type AiDiagnostics = { attempted: boolean; provider: string; model: string; promptVersion: string; candidateCount: number; selectedCandidate?: number | null; status: AiDiagnosticsStatus; failureReason?: string | null; appliedMapping?: AiAppliedMappingEntry[] }

export type AiDiagnosticsStatus = "accepted" | "failed" | "rejected"

export type ApiKeyCreatePayload = { name: string; key: string; provider: string | null }

export type ApiKeyDeleteResponse = { success: boolean; error?: string | null }

export type ApiKeyItem = { id: string; name: string; key: string; provider: string; isActive: boolean; createdAt: string; updatedAt: string }

export type ApiKeyMutationResponse = { success: boolean; key?: ApiKeyItem | null; error?: string | null }

export type ApiKeyValidationResponse = { isValid: boolean; error?: string | null }

/**
 * Information about a backup file
 */
export type BackupInfo = { name: string; date: string; size: number }

/**
 * Result of a backup operation
 */
export type BackupResult = { success: boolean; name?: string | null; error?: string | null }

export type CalibrationResponse = { deviceType: string; rSquared: number; slope: number; intercept: number; hysteresis: number; stdev: number; status: string; lastCalDate?: string | null; calibrationDate?: string | null; issues: string[]; rawData: string }

export type ConflictItem = { id: string; mergeEventId: string | null; experimentId: string | null; fieldName: string; localValue: string | null; incomingValue: string | null; resolution: string | null; status: string; createdAt: string; resolvedAt: string | null }

export type ExperimentDeleteResponse = { success: boolean; error?: string | null }

/**
 * Lightweight existence check — returns only the IDs that exist in the DB.
 */
export type ExperimentExistenceResponse = { existingIds: string[] }

export type ExperimentGetBatchResponse = { success: boolean; experiments: StoredExperiment[]; error?: string | null }

export type ExperimentGetResponse = { success: boolean; experiment?: StoredExperiment | null; error?: string | null }

/**
 * Lightweight experiment summary for list/table views.
 * Excludes heavy payloads: rawPoints, metrics, calibration.
 */
export type ExperimentListItem = { id: string; createdAt: string; updatedAt: string; name: string; fieldName: string | null; operatorName: string | null; wellNumber: string | null; testId: string | null; originalFilename: string; testDate: string; instrumentType: string; geometry: string | null; geometrySource: string | null; waterSource: string; waterParams: JsonValue | null; fluidType: string; testGroup: string; testSubGroup: string | null; testCategory?: string | null; testType?: string | null; dominantPattern?: string | null; maxViscosity: number | null; avgViscosity: number | null; durationSeconds: number | null; avgTemperatureC: number | null; maxTemperatureC: number | null; reagents: StoredExperimentReagent[]; user: StoredExperimentUser | null; laboratory: StoredExperimentLaboratory | null }

export type ExperimentPayloadItem = { id: string; experimentId: string; importBatchId: string | null; payloadVersion: number; payloadFormat: string; contentFingerprint: string; sourceLabId: string | null; isCanonical: boolean; createdAt: string }

export type ExperimentSavePayload = { name: string; fieldName: string | null; operatorName: string | null; wellNumber: string | null; testId: string | null; originalFilename: string; testDate: string; instrumentType: string; geometry: string | null; geometrySource: string | null; waterSource: string; waterParams: JsonValue | null; fluidType: string; testGroup: string; testSubGroup: string | null; testCategory?: string | null; testType?: string | null; dominantPattern?: string | null; metrics: JsonValue; rawPoints?: JsonValue[]; calibration: JsonValue | null; reagents?: StoredExperimentReagent[]; overwrite: boolean | null; laboratoryId?: string | null; parsedBy?: string | null; parseSource?: string | null; timeRangeMin?: number | null; timeRangeMax?: number | null; viscosityMin?: number | null; pressureMax?: number | null; extraFields?: JsonValue | null }

export type ExperimentSaveResponse = { success: boolean; experimentId?: string | null; message?: string | null; error?: string | null; code?: string | null }

export type ExperimentsCountResponse = { count: number }

export type ExperimentsFilterMetadataResponse = { instrumentTypes: string[]; fluidTypes: string[]; geometries: string[]; reagentNames: string[]; laboratoryNames: string[]; fieldNames: string[]; waterSources: string[]; testCategories: string[]; testTypes: string[] }

export type ExperimentsListQuery = { page?: number | null; limit?: number | null; laboratoryId?: string | null; searchQuery?: string | null; testName?: string | null; laboratoryName?: string | null; fieldName?: string | null; operatorName?: string | null; wellNumber?: string | null; waterSource?: string | null; fluidType?: string | null; instrumentType?: string | null; geometry?: string | null; batchNumber?: string | null; reagentName?: string | null; reagentNames?: string[] | null; dateFrom?: string | null; dateTo?: string | null; durationMin?: string | null; durationMax?: string | null; tempMin?: string | null; tempMax?: string | null; viscosityMin?: string | null; viscosityMax?: string | null; testCategory?: string | null; testType?: string | null; 
/**
 * Keyset cursor: when set, skip OFFSET and instead use WHERE e.createdAt < cursor_date
 * OR (e.createdAt = cursor_date AND e.id > cursor_id). Takes priority over `page`.
 */
afterId?: string | null; 
/**
 * Column to sort by. Validated server-side against an explicit whitelist.
 * Ignored when using keyset cursor (cursor requires deterministic ordering).
 */
sortBy?: string | null; 
/**
 * Sort direction: "asc" or "desc". Defaults to "desc" when absent.
 */
sortDir?: string | null }

export type ExperimentsListResponse = { experiments: ExperimentListItem[]; pagination: ExperimentsPagination }

export type ExperimentsPagination = { page: number; limit: number; total: number; totalPages: number; 
/**
 * Last item ID from this page — pass as `afterId` in next request
 * for keyset (cursor-based) pagination instead of OFFSET.
 */
nextCursor?: string | null }

export type FilenameMetadataResponse = { testId?: string | null; testType?: string | null; testTypeFull?: string | null; fieldName?: string | null; destination?: string | null; waterSource?: string | null; temperature?: number | null; recipe?: RecipeComponentResponse[] | null }

export type FixtureItem = { name: string; displayName: string }

export type FixtureReadResponse = { success: boolean; filename?: string | null; bytes?: number[] | null; error?: string | null }

export type FixturesListResponse = { success: boolean; fixtures: FixtureItem[]; count: number; error?: string | null }

export type ImportBatchItem = { id: string; sourceLabId: string | null; sourceSystem: string | null; sourceAppVersion: string | null; importedByUserId: string | null; fileName: string | null; checksum: string | null; notes: string | null; experimentsImported: number; duplicatesDetected: number; status: string; createdAt: string; updatedAt: string }

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

export type LaboratoryDeleteResponse = { success: boolean; error?: string | null }

export type LaboratoryMutationResponse = { success: boolean; laboratory?: StoredLaboratory | null; error?: string | null }

export type LaboratoryUpsertPayload = { name: string; description?: string | null; location?: string | null }

export type LastContextReagent = { reagentId: string; reagentName: string; concentration: number; unit: string; batchNumber: string | null; productionDate: string | null }

export type LastContextResponse = { fieldName: string | null; operatorName: string | null; waterSource: string | null; reagents: LastContextReagent[] }

/**
 * The authoritative result of a license check, computed in Rust.
 * Sent to the frontend as a single atomic snapshot.
 */
export type LicenseCheckResult = { status: LicenseStatus; source: LicenseSource; features: LicenseFeatures; 
/**
 * License key (masked for display, e.g. "RHEO-****-****-ABCD")
 */
key: string | null; 
/**
 * License type string from server
 */
licenseType: string | null; 
/**
 * Customer name from license
 */
customerName: string | null; 
/**
 * License expiry date (ISO 8601)
 */
expiresAt: string | null; 
/**
 * Days remaining until expiry (negative = past due)
 */
daysRemaining: number | null; 
/**
 * Experiments remaining (demo mode only)
 */
experimentsRemaining: number | null; 
/**
 * Human-readable message
 */
message: string | null; 
/**
 * Whether the UI should show a warning banner
 */
showWarning: boolean }

/**
 * Feature flags determining what the user can do.
 */
export type LicenseFeatures = { maxExperiments: number; maxComparisonExperiments: number; exportPdf: boolean; exportExcel: boolean; aiParsing: boolean; comparison: boolean; watermark: boolean; calibrationAnalysis: boolean; calibrationParsing: boolean; chandler5550Support: boolean; bslR1Support: boolean }

/**
 * Where the license came from
 */
export type LicenseSource = "key" | "demo"

/**
 * Authoritative license status determined entirely in Rust.
 */
export type LicenseStatus = 
/**
 * Full license is active and valid
 */
"active" | 
/**
 * License expired but within grace period
 */
"grace" | 
/**
 * Demo trial is active
 */
"demo" | 
/**
 * Demo trial has expired
 */
"demo_expired" | 
/**
 * License has expired (past grace period)
 */
"expired" | 
/**
 * License is invalid / tampered / revoked
 */
"invalid" | 
/**
 * License was revoked by the server
 */
"revoked"

/**
 * License type (matches server-side types).
 * 
 * Release-channel mapping used by `get_update_channel`:
 * 
 * | License type | Update channel | Who receives builds first |
 * |--------------|----------------|---------------------------|
 * | `Superuser`  | `alpha`        | Project owner (personal QA tier) |
 * | `Developer`  | `beta`         | Internal dev team |
 * | everything   | `stable`       | End users |
 * 
 * The alpha → beta → stable promotion is a **manual** pipeline: the owner
 * ships a build to `alpha`, validates it on their machine, then promotes it
 * to `beta`; once the dev team confirms, it moves to `stable`.
 */
export type LicenseType = "demo" | "trial" | "standard" | "enterprise" | "developer" | 
/**
 * Top-tier personal licence for the project owner. Receives builds on
 * the `alpha` channel before Developer licences see them on `beta`.
 */
"superuser"

/**
 * Result of a database merge (import) operation
 */
export type MergeResult = { success: boolean; error?: string | null; 
/**
 * Number of experiments added from the import source
 */
imported: number; 
/**
 * Number of experiments skipped (already existed)
 */
skipped: number; 
/**
 * FK violations detected after merge (non-fatal warnings)
 */
warnings?: string[] | null }

export type OperatorDeleteResponse = { success: boolean; error?: string | null }

export type OperatorMutationResponse = { success: boolean; operator?: StoredOperator | null; error?: string | null }

export type OperatorUpsertPayload = { name: string; position?: string | null }

export type ParseFileResponse = { success: boolean; source: string; data: ParsedPoint[]; metadata: ParseMetadata; summary: ParseSummary }

export type ParseMetadata = { filename: string; instrumentType?: string | null; geometry?: string | null; geometrySource?: string | null; usedAI: boolean; testDate?: string | null; aiDiagnostics?: AiDiagnostics | null; filenameMetadata?: FilenameMetadataResponse | null; calibration?: CalibrationResponse | null }

export type ParseRequest = { filename: string; 
/**
 * Preferred on desktop: Rust reads the file from disk — avoids 8× JSON array conversion over IPC.
 */
filePath: string | null; 
/**
 * Web / WASM fallback only — present when filePath is absent.
 */
bytes: number[] | null; 
/**
 * When true, skip heuristic parsing and use Groq AI for column mapping.
 */
forceAi: boolean | null; 
/**
 * AI model override (defaults to llama-4-scout).
 */
aiModel: string | null }

export type ParseSummary = { pointCount: number; timeRange?: TimeRange | null; viscosityRange?: SummaryRangeWithAvg | null; temperatureRange?: SummaryRangeWithAvg | null; pressureRange?: SummaryRange | null }

export type ParsedPoint = { time_sec: number; viscosity_cp: number; temperature_c: number; speed_rpm: number; shear_rate_s1: number; shear_stress_pa: number; pressure_bar: number; bath_temperature_c?: number | null }

export type ParserArtifactItem = { id: string; experimentId: string; importBatchId: string | null; parserVersion: string; schemaVersion: string; contentFingerprint: string; promotedToHot: boolean; createdAt: string }

export type ReagentDeleteResponse = { success: boolean; error?: string | null }

export type ReagentMutationResponse = { success: boolean; reagent?: StoredReagent | null; error?: string | null }

export type ReagentUpsertPayload = { name: string; category: string; manufacturer: string | null; country: string | null; description: string | null; activeSubstance: string | null; form: string | null }

export type RecipeComponentResponse = { abbreviation: string; concentration: number; unit: string; category?: string | null; reagentId?: string | null; reagentName?: string | null }

export type ReportArtifactItem = { id: string; experimentId: string; importBatchId: string | null; reportType: string; templateVersion: string | null; storagePath: string | null; binarySha256: string | null; sizeBytes: number | null; createdAt: string }

export type SimpleResult = { success: boolean; message: string | null; error: string | null; deletedCount: number | null }

export type StoredExperiment = { id: string; createdAt: string; updatedAt: string; name: string; fieldName: string | null; operatorName: string | null; wellNumber: string | null; testId: string | null; originalFilename: string; testDate: string; instrumentType: string; geometry: string | null; geometrySource: string | null; waterSource: string; waterParams: JsonValue | null; fluidType: string; testGroup: string; testSubGroup: string | null; testCategory?: string | null; testType?: string | null; dominantPattern?: string | null; metrics: JsonValue; rawPoints: JsonValue[]; calibration: JsonValue | null; reagents: StoredExperimentReagent[]; maxViscosity: number | null; avgViscosity: number | null; user: StoredExperimentUser | null; laboratory: StoredExperimentLaboratory | null; parsedBy?: string | null; parseSource?: string | null; timeRangeMin?: number | null; timeRangeMax?: number | null; viscosityMin?: number | null; pressureMax?: number | null; extraFields?: JsonValue | null }

export type StoredExperimentLaboratory = { id: string; name: string }

export type StoredExperimentReagent = { reagentId: string | null; reagentName: string | null; concentration: number; unit: string; batchNumber: string | null; productionDate: string | null; category: string | null; reagent: StoredReagentDescriptor | null }

export type StoredExperimentUser = { id: string; name: string; email: string | null }

export type StoredLaboratory = { id: string; name: string; description?: string | null; location?: string | null; createdAt: string; updatedAt: string }

export type StoredOperator = { id: string; name: string; position?: string | null; isActive: boolean; createdAt: string; updatedAt: string }

export type StoredReagent = { id: string; name: string; category: string; manufacturer: string | null; country: string | null; description: string | null; activeSubstance: string | null; form: string | null; createdAt: string; updatedAt: string }

export type StoredReagentDescriptor = { name: string; category: string | null }

export type SummaryRange = { min: number; max: number }

export type SummaryRangeWithAvg = { min: number; max: number; avg: number }

export type SyncInboxItem = { id: string; remoteEventId: string; sourceLabId: string | null; sourceSystem: string | null; status: string; receivedAt: string; processedAt: string | null; importBatchId: string | null }

export type SyncOutboxItem = { id: string; entityType: string; entityId: string; operation: string; status: string; retryCount: number; nextAttemptAt: string | null; lastError: string | null; createdAt: string; processedAt: string | null }

export type SyncStatusResponse = { outboxPending: number; outboxFailed: number; inboxPending: number; conflictsOpen: number; lastSyncAt: string | null }

export type TimeRange = { start: number; end: number; durationMinutes: number }

export type WaterSourcesResponse = { waterSources: string[] }

