#!/bin/bash
#
# RheoLab License Server - Install Script
# For Ubuntu 22.04+ / 24.04 VPS
#
# Usage:
#   1. Upload the entire license-server/ directory to the target server
#   2. Run: sudo bash install.sh
#
# This script:
#   - Installs LAMP stack (Apache, MySQL, PHP 8.x)
#   - Creates database and MySQL user (with restricted privileges)
#   - Generates RSA key pair for license signing
#   - Copies source files to /var/www/license-server/
#   - Generates config.php with random credentials
#   - Creates MySQL option file for backups (/root/.my.cnf)
#   - Sets up Apache vhost + SSL via Let's Encrypt
#   - Configures UFW firewall, fail2ban, unattended-upgrades
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "========================================"
echo "  RheoLab License Server Installer"
echo "========================================"
echo ""

# ── Check root ────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: This script must be run as root (sudo bash install.sh)"
    exit 1
fi

# ── Configuration (random passwords) ─────────────────────────
DB_NAME="rheolab_license"
DB_USER="license_user"
DB_PASS="$(openssl rand -base64 24)"
ADMIN_USER="admin"
ADMIN_PASS="$(openssl rand -base64 24)"
LICENSE_SECRET="$(openssl rand -hex 32)"
WEB_DIR="/var/www/license-server"

# Prompt for domain (needed for SSL)
read -rp "Domain name (e.g. license.vizbuka.ru): " DOMAIN
if [ -z "$DOMAIN" ]; then
    echo "Error: domain is required for SSL setup."
    exit 1
fi

echo ""
echo "[1/10] Updating system..."
apt update && apt upgrade -y

echo "[2/10] Installing LAMP + tools..."
DEBIAN_FRONTEND=noninteractive apt install -y \
    apache2 \
    mysql-server \
    php php-mysql php-curl php-json php-mbstring php-xml \
    libapache2-mod-php \
    certbot python3-certbot-apache \
    ufw fail2ban unattended-upgrades \
    curl openssl \
    python3-pip python3-venv

python3 -m pip install --break-system-packages boto3

echo "[3/10] Configuring MySQL..."
mysql -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';"
# Least-privilege: only SELECT, INSERT, UPDATE, DELETE
mysql -e "GRANT SELECT, INSERT, UPDATE, DELETE ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"

echo "[4/10] Importing database schema..."
mysql ${DB_NAME} < "${SCRIPT_DIR}/database.sql"

echo "[5/10] Deploying source files..."
mkdir -p "${WEB_DIR}"/{api,admin,includes,keys}

# Copy PHP source files from the repo
cp "${SCRIPT_DIR}/includes/db.php"           "${WEB_DIR}/includes/"
cp "${SCRIPT_DIR}/includes/helpers.php"      "${WEB_DIR}/includes/"
cp "${SCRIPT_DIR}/includes/license_payload.php" "${WEB_DIR}/includes/"
cp "${SCRIPT_DIR}/includes/rate_limiter.php" "${WEB_DIR}/includes/"
cp "${SCRIPT_DIR}/includes/sign_rsa.php"     "${WEB_DIR}/includes/"
cp "${SCRIPT_DIR}/api/activate.php"          "${WEB_DIR}/api/"
cp "${SCRIPT_DIR}/api/validate.php"          "${WEB_DIR}/api/"
cp "${SCRIPT_DIR}/api/status.php"            "${WEB_DIR}/api/"
cp "${SCRIPT_DIR}/api/deactivate.php"        "${WEB_DIR}/api/"
cp "${SCRIPT_DIR}/api/find_by_machine.php"   "${WEB_DIR}/api/"
cp "${SCRIPT_DIR}/api/find_all_by_machine.php" "${WEB_DIR}/api/"
cp "${SCRIPT_DIR}/api/register_demo.php"     "${WEB_DIR}/api/"
cp "${SCRIPT_DIR}/api/migrate_machine.php"   "${WEB_DIR}/api/"
cp "${SCRIPT_DIR}/api/update-channel.php"    "${WEB_DIR}/api/"
cp "${SCRIPT_DIR}/admin/index.php"           "${WEB_DIR}/admin/"

# .htaccess
if [ -f "${SCRIPT_DIR}/.htaccess" ]; then
    cp "${SCRIPT_DIR}/.htaccess" "${WEB_DIR}/"
fi

# releases/.htaccess (channel-aware update routing)
if [ -f "${SCRIPT_DIR}/releases.htaccess" ]; then
    mkdir -p "${WEB_DIR}/releases"
    cp "${SCRIPT_DIR}/releases.htaccess" "${WEB_DIR}/releases/.htaccess"
fi

echo "[6/10] Generating RSA key pair..."
openssl genpkey -algorithm RSA -out "${WEB_DIR}/keys/license_private.pem" -pkeyopt rsa_keygen_bits:2048
chmod 600 "${WEB_DIR}/keys/license_private.pem"

echo "[7/10] Generating config.php..."
ADMIN_PASS_HASH=$(php -r "echo password_hash('${ADMIN_PASS}', PASSWORD_BCRYPT);")

cat > "${WEB_DIR}/config.php" << CONFIGEOF
<?php
/**
 * RheoLab License Server - Production Configuration
 * Generated by install.sh on $(date -Iseconds)
 */

define('DEBUG', false);

define('DB_HOST', 'localhost');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
define('DB_CHARSET', 'utf8mb4');

define('LICENSE_SECRET', '${LICENSE_SECRET}');

define('GRACE_PERIOD_DAYS', 30);
define('LICENSE_CACHE_DAYS', 7);

define('ALLOWED_ORIGINS', [
    'tauri://localhost',
    'https://localhost'
]);

define('ADMIN_USER', '${ADMIN_USER}');
define('ADMIN_PASS_HASH', '${ADMIN_PASS_HASH}');

define('LOGIN_MAX_ATTEMPTS', 5);
define('LOGIN_LOCKOUT_SECONDS', 900);

error_reporting(0);
ini_set('display_errors', '0');
date_default_timezone_set('Asia/Yekaterinburg');
CONFIGEOF

chmod 600 "${WEB_DIR}/config.php"

echo "[8/10] Configuring Apache..."
cat > /etc/apache2/sites-available/license.conf << APACHEEOF
<VirtualHost *:80>
    ServerName ${DOMAIN}
    DocumentRoot ${WEB_DIR}
    <Directory ${WEB_DIR}>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    <FilesMatch "^(config\\.php)\$">
        Require all denied
    </FilesMatch>
    <Directory ${WEB_DIR}/includes>
        Require all denied
    </Directory>
    <Directory ${WEB_DIR}/keys>
        Require all denied
    </Directory>
    ErrorLog \${APACHE_LOG_DIR}/license-error.log
    CustomLog \${APACHE_LOG_DIR}/license-access.log combined
</VirtualHost>
APACHEEOF

a2ensite license.conf
a2enmod rewrite headers
a2dissite 000-default.conf 2>/dev/null || true
systemctl reload apache2

echo "[9/10] Setting up SSL (Let's Encrypt)..."
certbot --apache -d "${DOMAIN}" --non-interactive --agree-tos --redirect \
    --email "admin@${DOMAIN}" || echo "  WARNING: SSL setup failed. Run manually: certbot --apache -d ${DOMAIN}"

echo "[10/10] Setting permissions & security..."
chown -R www-data:www-data "${WEB_DIR}"
chmod -R 755 "${WEB_DIR}"
chmod 600 "${WEB_DIR}/config.php"
chmod 600 "${WEB_DIR}/keys/license_private.pem"
chmod 700 "${WEB_DIR}/keys"

# MySQL option file for backups (no password in scripts)
cat > /root/.my.cnf << MYCNFEOF
[mysqldump]
user=${DB_USER}
password=${DB_PASS}

[mysql]
user=${DB_USER}
password=${DB_PASS}
MYCNFEOF
chmod 600 /root/.my.cnf

if [ -f "${SCRIPT_DIR}/s3-backup.env.example" ]; then
    cp "${SCRIPT_DIR}/s3-backup.env.example" /root/.license-server-s3.env
    chmod 600 /root/.license-server-s3.env
fi

# Backup cron job (daily at 3 AM)
if [ -f "${SCRIPT_DIR}/backup.sh" ]; then
    cp "${SCRIPT_DIR}/backup.sh" /usr/local/bin/backup-license.sh
    chmod +x /usr/local/bin/backup-license.sh
    mkdir -p /var/backups/license-server
    # Add cron if not already present
    if ! crontab -l 2>/dev/null | grep -q "backup-license"; then
        (crontab -l 2>/dev/null; echo "0 3 * * * /usr/local/bin/backup-license.sh >> /var/log/license-backup.log 2>&1") | crontab -
    fi
fi

if [ -f "${SCRIPT_DIR}/s3_helper.py" ]; then
    cp "${SCRIPT_DIR}/s3_helper.py" /usr/local/bin/license-s3-helper.py
    chmod +x /usr/local/bin/license-s3-helper.py
fi

if [ -f "${SCRIPT_DIR}/cleanup.sh" ]; then
    cp "${SCRIPT_DIR}/cleanup.sh" /usr/local/bin/cleanup-license.sh
    chmod +x /usr/local/bin/cleanup-license.sh
    if ! crontab -l 2>/dev/null | grep -q "cleanup-license"; then
        (crontab -l 2>/dev/null; echo "30 3 * * * /usr/local/bin/cleanup-license.sh >> /var/log/license-backup.log 2>&1") | crontab -
    fi
fi

if [ -f "${SCRIPT_DIR}/admin-backup-trigger.sh" ]; then
    cp "${SCRIPT_DIR}/admin-backup-trigger.sh" /usr/local/bin/license-admin-backup-trigger.sh
    chmod 750 /usr/local/bin/license-admin-backup-trigger.sh
    chown root:www-data /usr/local/bin/license-admin-backup-trigger.sh
fi

if [ -f "${SCRIPT_DIR}/admin-verify-backup.sh" ]; then
    cp "${SCRIPT_DIR}/admin-verify-backup.sh" /usr/local/bin/license-admin-verify-backup.sh
    chmod 750 /usr/local/bin/license-admin-verify-backup.sh
    chown root:www-data /usr/local/bin/license-admin-verify-backup.sh
fi

if command -v sudo >/dev/null 2>&1; then
    cat > /etc/sudoers.d/license-admin-maintenance << 'SUDOEOF'
www-data ALL=(root) NOPASSWD: /usr/local/bin/license-admin-backup-trigger.sh, /usr/local/bin/license-admin-verify-backup.sh
SUDOEOF
    chmod 440 /etc/sudoers.d/license-admin-maintenance
    visudo -cf /etc/sudoers.d/license-admin-maintenance >/dev/null
fi

# Firewall
ufw allow OpenSSH
ufw allow 'Apache Full'
ufw --force enable

# Fail2ban (ensure running)
systemctl enable fail2ban
systemctl start fail2ban

# ── Save credentials ─────────────────────────────────────────
CREDENTIALS_FILE="/root/.rheolab-credentials"
cat > "${CREDENTIALS_FILE}" << CREDEOF
# RheoLab License Server Credentials
# Generated: $(date -Iseconds)
# KEEP THIS FILE SECURE — contains all passwords

DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASS=${DB_PASS}

ADMIN_USER=${ADMIN_USER}
ADMIN_PASS=${ADMIN_PASS}

LICENSE_SECRET=${LICENSE_SECRET}
DOMAIN=${DOMAIN}
CREDEOF
chmod 600 "${CREDENTIALS_FILE}"

echo ""
echo "========================================"
echo "  ✅ УСТАНОВКА ЗАВЕРШЕНА!"
echo "========================================"
echo ""
echo "Domain:       https://${DOMAIN}"
echo "Admin:        https://${DOMAIN}/admin/"
echo "API:          https://${DOMAIN}/api/"
echo ""
echo "Credentials:  cat ${CREDENTIALS_FILE}"
echo "MySQL cnf:    /root/.my.cnf"
echo "RSA key:      ${WEB_DIR}/keys/license_private.pem"
echo "Backups:      /var/backups/license-server/ (daily 3 AM)"
echo "S3 config:    /root/.license-server-s3.env"
echo "Cleanup:      /usr/local/bin/cleanup-license.sh (daily 3:30 AM)"
echo ""
echo "Test: curl https://${DOMAIN}/api/status.php?key=TEST-1234-5678-ABCD"
echo ""
echo "========================================"
